### ISSUE TITLE
Doesn't authenticate SendGrid

### ISSUE THREAD

**Issue by sevab** [barsoom/gridlook#7]
Please correct me if I'm wrong, but it seems that you don't actually authenticate sendgrid webhook requests?

I see that there's a [`authenticate_with_basic_auth`](https://github.com/barsoom/gridlook/blob/master/app/controllers/application_controller.rb#L12) method in your ApplicationController for incoming SendGrid webhook requests.  However, `gridhook` gem's `event_controller` inherits from the `ActionController::Base` and hence SendGrid's POST request will skip this authentication check?

**Comment by tskogberg** [comment]
Yes you're right. Moving basic auth to the application controller did exclude basic auth from the Gridhook /events end-point.

Thank you for reporting this security issue!

**Comment by tskogberg** [comment]
Unfortunately I can't test the fix i pushed. I'll verify that it works tomorrow.

**Comment by henrik** [comment]
To add in some more background here: this auth used to be a middleware, then it was [accidentally moved to ApplicationController to fix another issue](https://github.com/barsoom/gridlook/commit/ffb87e66ded2f2ba1eb88be49c25a62482d23966). Now it's been moved back.

**Comment by tskogberg** [comment]
Update:

The fix works. We have also added tests to ensure we use basic auth for the /events end-point.

So will close this issue. Thanks again @sevab for reporting it!
