### ISSUE TITLE
Add Rails Engine or Gem support [or API?]

### ISSUE THREAD

**Issue by vasilakisfil** [barsoom/gridlook#8]
Thanks for the lib! What I would like to see is to be able to integrate it in other Rails projects, like an engine. 

Probably that's quite tough but it would be nice to be possible to at least integrate some parts of it, like the models. So that from the same project I can talk to all tables of gridlook by just inheriting the gridlook's model classes. Otherwise, if I want to have some logic based on the data saved in gridlook, I have re-implement the models in my project.

**Comment by henrik** [comment]
Thank you for the suggestion! This is not something we currently see ourselves using, so I don't think we will add it or accept pull requests for it if they would make the codebase much more complex. But if it's optional and does not make things much more complex, a PR would be welcome.

Another idea is adding an API to Gridlook, to show data in other projects. That could be quite useful for us as well – so PRs for that would be great. Maybe someone in our team will experiment with that some day.

One thing you could do is use the Gridlook database from another project – but you would indeed need to reimplement the models like you say.
